title: GoCD plugins
author: bdpiparva

minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

theme: minima
exclude:
  - Gemfile
  - Gemfile.lock